[llvm] Work around C++20 error:
interpreter/llvm/src/lib/IR/DebugInfo.cpp:658:25: error: ambiguous overload for ‘operator!=’ (operand types are ‘llvm::DILocation*’ and ‘llvm::DebugLoc’)
  658 |                 if (Loc != DebugLoc())
      |                     ~~~ ^~ ~~~~~~~~~~
      |                     |      |
      |                     |      llvm::DebugLoc
      |                     llvm::DILocation*

This code does not exist in upstream llvm anymore, and was never fixed before it got removed.